//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PD_Areas> PD_Areas { get; set; }
        public virtual DbSet<PD_BASETYPE> PD_BASETYPE { get; set; }
        public virtual DbSet<PD_TYPE> PD_TYPE { get; set; }
        public virtual DbSet<SYS_FUNCTION> SYS_FUNCTION { get; set; }
        public virtual DbSet<SYS_ORGANIZATION> SYS_ORGANIZATION { get; set; }
        public virtual DbSet<SYS_PART_FUNC> SYS_PART_FUNC { get; set; }
        public virtual DbSet<UR_PART> UR_PART { get; set; }
        public virtual DbSet<UR_USERS> UR_USERS { get; set; }
    }
}
