//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PD_TYPE
    {
        public int Id { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string ImgName { get; set; }
        public string ImgPath { get; set; }
        public string ImgType { get; set; }
        public Nullable<int> ImgSize { get; set; }
        public byte[] ImgPic { get; set; }
    }
}
