//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ORGANIZATION
    {
        public int ORG_ID { get; set; }
        public string ORG_CITY { get; set; }
        public string ORG_LEVEL { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_LAYER { get; set; }
        public string ORG_PARENT_ID { get; set; }
        public Nullable<short> ORG_IS_LEAF { get; set; }
        public string ORG_MANAGER { get; set; }
        public string ORG_MANAGER_PHONE { get; set; }
        public string ORG_ADDRESS { get; set; }
        public string ORG_BILL_ADDRESS { get; set; }
        public string ORG_POST_CODE { get; set; }
        public string ORG_TELEPHONE { get; set; }
        public string ORG_UNITE { get; set; }
        public Nullable<short> ORG_ACTIVE { get; set; }
        public string ORG_NOTE { get; set; }
        public string ORG_CREATE_ID { get; set; }
        public Nullable<System.DateTime> ORG_CREATE_DATE { get; set; }
        public string ORG_UPDATE_ID { get; set; }
        public Nullable<System.DateTime> ORG_UPDATE_DATE { get; set; }
        public string ORG_UNUSED1 { get; set; }
        public string ORG_UNUSED2 { get; set; }
        public Nullable<int> ORG_UNUSED3 { get; set; }
        public Nullable<int> ORG_UNUSED4 { get; set; }
    }
}
