//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_ApiLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string 名称 { get; set; }
        public string Url { get; set; }
        public string PostData { get; set; }
        public string 返回信息 { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string 备注 { get; set; }
        public string IP { get; set; }
        public string Host { get; set; }
        public string UserAgent { get; set; }
    }
}
