//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Finance
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> UseMoney { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> CoinMoney { get; set; }
        public string Memo { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> ProType { get; set; }
        public Nullable<int> IsBack { get; set; }
        public Nullable<int> BackUserId { get; set; }
    }
}
