//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Kefu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string RealName { get; set; }
        public Nullable<int> Level { get; set; }
        public string Photo { get; set; }
        public string QQ { get; set; }
        public string Weixin { get; set; }
        public string WeixinUrl { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> IsOnline { get; set; }
        public Nullable<int> IsChecked { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> WorkYear { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateId { get; set; }
    }
}
