//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Message
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<int> IsSystem { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> IsAlert { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
