//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_StateLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OrderType { get; set; }
        public string OrderId { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Host { get; set; }
        public string UserAgent { get; set; }
    }
}
