//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Trademark_Files
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OrderId { get; set; }
        public string TmName { get; set; }
        public string TmCls { get; set; }
        public Nullable<int> ApplyerId { get; set; }
        public string ImageFile { get; set; }
        public string ApplyNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public string FilePath { get; set; }
        public string Business { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> IsPost { get; set; }
        public Nullable<int> PostNo { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
