//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Trademark
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> KefuId { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Name { get; set; }
        public string Cls { get; set; }
        public string Explanation { get; set; }
        public Nullable<int> ApplyerId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ApplyNumber { get; set; }
        public string Status { get; set; }
        public string DelegationFile { get; set; }
        public string GoodsNameArray { get; set; }
        public string ImageFile { get; set; }
        public string ImageFile2 { get; set; }
        public Nullable<int> IsColor { get; set; }
        public Nullable<int> Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditMemo { get; set; }
        public Nullable<System.DateTime> SubmitToRegistration { get; set; }
        public Nullable<int> IsPay { get; set; }
        public Nullable<int> GoodNum { get; set; }
        public Nullable<decimal> OfficialMoney { get; set; }
        public Nullable<decimal> ServiceMoney { get; set; }
        public string AnalysisFile { get; set; }
        public string 提交公司 { get; set; }
        public Nullable<int> IsCheck { get; set; }
    }
}
