//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_User
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string Nickname { get; set; }
        public string RealName { get; set; }
        public string HeadPhoto { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string Weixin { get; set; }
        public string Token { get; set; }
        public string Retoken { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Idcard { get; set; }
        public Nullable<int> IsTrueId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string GradeName { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
        public string GradeReason { get; set; }
        public Nullable<decimal> UseMoney { get; set; }
        public Nullable<decimal> FrozenMoney { get; set; }
        public Nullable<decimal> CostMoeny { get; set; }
        public Nullable<decimal> SumMoney { get; set; }
        public Nullable<decimal> WithdrawalMoney { get; set; }
        public Nullable<decimal> InvoiceMoney { get; set; }
        public Nullable<decimal> CoinMoney { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateId { get; set; }
    }
}
