//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keven.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UR_USERS
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_ORG_ID { get; set; }
        public string USER_LOGIN_NAME { get; set; }
        public string USER_LOGIN_PASSWD { get; set; }
        public Nullable<System.DateTime> USER_LOGIN_DATE { get; set; }
        public string USER_PHONE { get; set; }
        public string USER_MOBILE { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_WORK_NO { get; set; }
        public string USER_SEX { get; set; }
        public Nullable<System.DateTime> USER_BIRTHDAY { get; set; }
        public string USER_WORKED { get; set; }
        public string USER_EDUCATION { get; set; }
        public string USER_ORIGIN { get; set; }
        public string USER_TITLE { get; set; }
        public string USER_WORK_LIMIT { get; set; }
        public string USER_IDENT_NO { get; set; }
        public Nullable<System.DateTime> USER_IN_DATE { get; set; }
        public string USER_AREA { get; set; }
        public string USER_ADDRESS { get; set; }
        public string USER_POSTAL { get; set; }
        public Nullable<short> USER_ACTIVE { get; set; }
        public Nullable<short> USER_OUT { get; set; }
        public Nullable<System.DateTime> USER_OUT_DATE { get; set; }
        public string USER_NOTE { get; set; }
        public string USER_CREATE_ID { get; set; }
        public Nullable<System.DateTime> USER_CREATE_DATE { get; set; }
        public string USER_UPDATE_ID { get; set; }
        public Nullable<System.DateTime> USER_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> USER_PASSWD_CHANGE_DATE { get; set; }
        public Nullable<System.DateTime> USER_UNLOCK_DATE { get; set; }
        public Nullable<short> USER_ADMIN { get; set; }
        public string USER_UNUSED1 { get; set; }
        public string USER_UNUSED2 { get; set; }
        public Nullable<int> USER_UNUSED3 { get; set; }
        public Nullable<int> USER_UNUSED4 { get; set; }
        public Nullable<int> USER_CHANNEL_ID { get; set; }
        public Nullable<int> USER_PART { get; set; }
    }
}
